project:
  type: website

website:
  title: "Experiment Results"
  navbar:
    background: primary
    left:
      - text: "Overview"
        href: index.qmd
      - text: "Simulation Results"
        href: simulation/simulation.html

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true
    page-layout: custom