project:
  type: website

website:
  title: "Research Summary"
  navbar:
    background: primary
    left:
      - text: "Experiment Results"
        href: analysis.qmd
      - text: "Try Simulation"
        href: simulation/simulation.html

format:
  html:
    theme: cosmo
    css: styles.css
    code-fold: true
    page-layout: article